---
pacman_packages:
  - alacritty
  - base-devel
  - curl
  - fakeroot
  - firefox
  - git
  - neofetch
  - net-tools
  - openssh
  - pyenv
  - ttf-fira-code
  - zsh

aur_packages:
  - gvm
  - nerd-fonts-hack
  - pyenv-virtualenv
  - visual-studio-code-bin
  - wol-systemd
  # - ncspot

enable_wake_on_lan: false
wol_interface: enp5s0

background_url: https://drive.google.com/uc?export=download&id=1SHfbSD5SBpfJXsWNRDk4f_dngHC26kC6
shell: zsh
ohmyzsh_path: ~/.oh-my-zsh
gvm_install_version: go1.17.6
nvm_install_version: "16.13.2"
nvm_version: "v0.39.1"
pyenv_install_version: "3.10.1"

enable_kde: false
install_sway: false

kde_pac_packages:
  - plasma
  - plasma-wayland-session
  - kde-applications
  - sddm
# sway_pac_packages:
#   - sway
#   -
