---
pacman_packages:
  - neofetch
  - curl
  - net-tools
  - git
  - base-devel
  - zsh
  - rust
  - openssh
  - firefox
  - alacritty

aur_packages:
  - gvm
  - pyenv
  - wol-systemd
  - visual-studio-code-bin
  - vscodium-bin
  # - ncspot

dotfiles_folder: ~/.dotfiles
dotfiles_repo: https://github.com/JonaVDM/dotfiles.git
dotfiles_files:
  - name: .zshrc
    dest: "~"
  - name: .gitconfig
    dest: "~"
  - name: .tmux.conf
    dest: "~"
dotfiles_folders:
  - name: alacritty
    dest: ~/.config/alacritty

enable_gnome: true
enable_wake_on_lan: true
wol_interface: enp5s0

background_url: https://drive.google.com/uc?export=download&id=1SHfbSD5SBpfJXsWNRDk4f_dngHC26kC6
shell: zsh
ohmyzsh_path: ~/.oh-my-zsh
gvm_install_version: go1.17.6
nvm_install_version: "16.13.2"
nvm_version: "v0.39.1"
pyenv_install_version: "3.10.1"

# https://extensions.gnome.org/extension-data/dash-to-dockmicxgx.gmail.com.v65.shell-extension.zip
gnome_extensions:
  - name: dash-to-dock@micxgx.gmail.com
    version: 71

code_extensions:
  - angular.ng-template
  - redhat.ansible
  - hookyqr.beautify
  - aaron-bond.better-comments
  - bungcip.better-toml
  - dart-code.dart-code
  - rid9.datetime
  - ms-azuretools.vscode-docker
  - mikestead.dotenv
  - editorconfig.editorconfig
  - dbaeumer.vscode-eslint
  - dart-code.flutter
  - mhutchie.git-graph
  - eamodio.gitlens
  - golang.go
  - pkief.material-icon-theme
  - arcticicestudio.nord-visual-studio-code
  - esbenp.prettier-vscode
  - jeroen-meijer.pubspec-assist
  - ms-python.python
  - mechatroner.rainbow-csv
  - humao.rest-client
  - matklad.rust-analyzer
  - ban.spellright
  - bradlc.vscode-tailwindcss
  - shyykoserhiy.vscode-spotify
