---
pacman_packages:
  - neofetch
  - curl
  - net-tools
  - git
  - base-devel
  - zsh
  - rust
  # - firefox
  # - alacritty

dotfiles_folder: ~/.dotfiles
dotfiles_repo: https://github.com/JonaVDM/dotfiles.git
dotfiles_files:
  - name: .zshrc
    dest: "~"
  - name: .gitconfig
    dest: "~"
  - name: .tmux.conf
    dest: "~"
dotfiles_folders:
  - name: alacritty
    dest: ~/.config/alacritty

aur_packages:
  - nvm
  - wol-systemd
  - gvm
  - pyenv
  # - ncspot

# enable_gnome: false
enable_wake_on_lan: false
wol_interface: en0
