---
pacman_packages:
  - neofetch
  - curl
  - net-tools
  - git
  - base-devel
  - zsh
  - neovim
  # - firefox
  # - alacritty

dotfiles_folder: ~/.dotfiles
dotfiles_repo: https://github.com/JonaVDM/dotfiles.git
dotfiles_files:
  - name: .zshrc
    dest: "~"
  - name: .gitconfig
    dest: "~"
  - name: .tmux.conf
    dest: "~"
dotfiles_folders:
  - name: alacritty
    dest: ~/.config/alacritty

install_pyenv: true

# aur_packages:
  # - ncspot

# enable_gnome: false
# enable_wake_on_lan: false
# install_gvm: false
# install_nvm: false
# isntall_rust: false
