---
- name: Setup Arch workstation
  hosts: all

  vars_files:
    - main.config.yml
    - packages.config.yml

  tasks:
    - name: ensure pacman cache is up to data
      become: true
      community.general.pacman:
        update_cache: true

    - name: update Dotfiles when sway is enabled
      ansible.builtin.set_fact:
        dotfiles_files: "{{ dotfiles_files + sway_dotfiles }}"
      when: enable_sway

    - ansible.builtin.import_tasks: "tasks/packages.yml"
    - ansible.builtin.import_tasks: "tasks/node.yml"
    - ansible.builtin.import_role:
        name: jonavdm.dotfiles
    - import_tasks: "tasks/tmux.yml"
    - import_tasks: "tasks/nvim.yml"
    - import_tasks: "tasks/shell.yml"

    - name: Make sure the Pictures folder exists
      ansible.builtin.file:
        path: ~/Pictures
        state: directory

    - name: Make sure the background image is downloaded
      ansible.builtin.get_url:
        url: "{{ background_url }}"
        dest: ~/Pictures/background.jpg
      when: background_url != "" and (enable_kde or enable_sway)

    - ansible.builtin.import_tasks: "tasks/zsh.yml"
      when: shell == "zsh"

    - import_tasks: "tasks/kde.yml"
      when: enable_kde

    - ansible.builtin.import_tasks: "tasks/nvidia.yml"
      when: nvidia_gpu

    - ansible.builtin.import_tasks: "tasks/sway.yml"
      when: enable_sway

    - name: Ensure wake on lan is on and enabled
      become: true
      ansible.builtin.service:
        name: wol@{{ wol_interface }}
        state: started
        enabled: true
      when: enable_wake_on_lan

    - include_role:
        name: jonavdm.versions
      vars:
        nvm_version: "{{ nvm_install_version }}"
        gvm_version: "{{ gvm_install_version }}" # TODO: Fix this, somehow
        py_version: "{{ pyenv_install_version }}"
