---
- name: Setup Arch workstation
  hosts: all

  vars_files:
    - config.yml

  tasks:
    - name: ensure pacman cache is up to data
      become: true
      community.general.pacman:
        update_cache: true

    - ansible.builtin.import_tasks: "tasks/packages.yml"
    - ansible.builtin.import_tasks: "tasks/node.yml"
    - ansible.builtin.import_role:
        name: jonavdm.dotfiles
    - import_tasks: "tasks/tmux.yml"
    - import_tasks: "tasks/nvim.yml"
    - import_tasks: "tasks/shell.yml"
    - import_tasks: "tasks/kde.yml"
      when: enable_kde

    - name: Ensure wake on lan is on and enabled
      become: true
      ansible.builtin.service:
        name: wol@{{ wol_interface }}
        state: started
        enabled: true
      when: enable_wake_on_lan

    - include_role:
        name: jonavdm.versions
      vars:
        nvm_version: "{{ nvm_install_version }}"
        gvm_version: "{{ gvm_install_version }}" # TODO: Fix this, somehow
        py_version: "{{ pyenv_install_version }}"
