---
- name: Setup Arch workstation
  hosts: all

  vars_files:
    - default.config.yml

  tasks:
    - name: ensure pacman cache is up to data
      become: true
      community.general.pacman:
        update_cache: true

    - import_tasks: "tasks/yay.yml"
    - import_tasks: "tasks/dotfiles.yml"

    - import_tasks: "tasks/pyenv.yml"
      when: install_pyenv

    - name: Ensure pacman packages are installed
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: latest
      with_items: "{{pacman_packages}}"

    # - name: ensure AUR packages are installed
    #   community.general.pacman:
    #     name: "{{ item }}"
    #     state: latest
    #     executable: yay
    #     # extra_args: --builddir /var/cache/yay
    #   with_items: "{{aur_packages}}"

    # - name: ensure tmux package maneger is installed
    # - name: ensure nvim config is downloaded
    # - name: ensure dotfiles are downloaded
    # - name: ensure current packages are upgraded
    # - name: ensure nvm is installed (when needed)
    # - name: ensure gvm is installed (when needed)
    # - name: ensure pyenv is installed (when needed)
    # - name: ensure gnome is installed (when needed)
    # - name: ensure wake on lan is enabled (when needed)
