---
nvidia_gpu: false

enable_wake_on_lan: false
wol_interface: enp5s0

enable_kde: false
enable_sway: true

shell: zsh
ohmyzsh_path: ~/.oh-my-zsh

nvm_version: "v0.39.1"
gvm_install_version: go1.17.6
nvm_install_version: "16.13.2"
pyenv_install_version: "3.10.1"

sway_dotfiles:
  - src: sway
    dest: ~/.config/sway
  - src: waybar
    dest: ~/.config/waybar
  - src: mako
    dest: ~/.config/mako

dotfiles_backgrounds:
  - src: ~/.dotfiles/nord-colors.png
    dest: ~/.Pictures/wallpaper.png
  - src: ~/.dotfiles/dark-top.jpg
    dest: ~/.Pictures/lock-screen.jpg
