---
- name: Setup Arch workstation
  hosts: all

  vars_files:
    - default.config.yml

  tasks:
    - name: ensure pacman cache is up to data
      become: true
      community.general.pacman:
        update_cache: true

    - import_tasks: "tasks/yay.yml"
    - import_tasks: "tasks/dotfiles.yml"
    - import_tasks: "tasks/tmux.yml"
    - import_tasks: "tasks/nvim.yml"

    - name: Ensure pacman packages are installed
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: latest
      with_items: "{{ pacman_packages }}"

    - name: ensure AUR packages are installed
      community.general.pacman:
        name: "{{ item }}"
        state: latest
        executable: yay
      with_items: "{{aur_packages}}"

    - name: Ensure wake on lan is on and enabled
      ansible.builtin.service:
        name: wol-systemd@{{ wol_interface }}
        state: started
        enabled: true
      when: enable_wake_on_lan

    # - name: ensure gnome is installed (when needed)
