---
pacman_packages:
  - alacritty
  - base-devel
  - curl
  - discord
  - fakeroot
  - firefox
  - git
  - neofetch
  - net-tools
  - openssh
  - pyenv
  - ttf-fira-code
  - zsh
  - github-cli
  - docker
  - fuse-overlayfs
  - libreoffice-still
  - unzip
  - zip

aur_packages:
  - gvm
  - nerd-fonts-hack
  - pyenv-virtualenv
  - visual-studio-code-bin
  - wol-systemd
  - docker-rootless-extras-bin
    # - ncspot

nvidia_driver:
  - mesa

kde_pac_packages:
  - plasma
  - plasma-wayland-session
  - kde-applications
  - sddm

sway_pac_packages:
  - sway
  - swaylock
  - swayidle
  - waybar
  - mako
  - qtkeychain
  - gnome-keyring
  - pulseaudio
  - playerctl
  - python-gobject
  - gtk3
  - pavucontrol
  - grim
  - wl-clipboard
  - slurp
  - rofi
