---
pacman_packages:
  - alacritty
  - base-devel
  - curl
  - discord
  - fakeroot
  - firefox
  - git
  - neofetch
  - net-tools
  - openssh
  - pyenv
  - ttf-fira-code
  - zsh

aur_packages:
  - gvm
  - nerd-fonts-hack
  - pyenv-virtualenv
  - visual-studio-code-bin
  - wol-systemd
  # - ncspot

nvidia_driver:
  - mesa

kde_pac_packages:
  - plasma
  - plasma-wayland-session
  - kde-applications
  - sddm

sway_pac_packages:
  - sway
  - wofi
  - waybar
  - mako
  - qtkeychain
  - gnome-keyring
