---
- name: Install required pacman packages
  community.general.pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ kde_pac_packages }}"
  become: true

- name: Enable sddm service
  ansible.builtin.service:
    name: sddm.service
    state: started
    enabled: true
