---
- name: Install NeoVIM
  become: true
  community.general.pacman:
    name: neovim
    state: latest

- name: Download nvim-config
  git:
    repo: https://github.com/JonaVDM/nvim-config.git
    dest: ~/.config/nvim
    update: true

- name: Install vim plug packages
  command: nvim --headless +PlugInstall +qa
