---
- name: Install the required packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ sway_pac_packages }}"

- name: Make sure .zprofile exists
  file:
    path: ~/.zprofile
    state: touch

- name: Insert auto start of sway into .zprofile
  blockinfile:
    path: ~/.zprofile
    block: |
      if [ -z $DISPLAY ] && [ "$(tty)" = "/dev/tty1" ]; then
        exec sway
      fi

- name: Temp clone the rofi-themes-collection repo
  ansible.builtin.git:
    repo: https://github.com/lr-tech/rofi-themes-collection.git
    dest: /tmp/rofi-themes-collection

- name: Make sure the rofi themes folder exists
  ansible.builtin.file:
    path: ~/.local/share/rofi/themes/
    state: directory

- name: Copy rofi theme over to the themes folder
  ansible.builtin.copy:
    src: /tmp/rofi-themes-collection/{{ rofi_theme }}
    dest: /.local/share/rofi/themes/

- name: Install powermenu
  kewlfft.aur.aur:
    name: rofi-power-menu
    state: latest
    use: yay
