---
- name: Check if yay is installed
  shell: yay --version
  register: yay_version_cmd
  changed_when: false
  ignore_errors: true

- name: Ensure git and base-devel is installed
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - base-devel

- name: Ensure yay is installed
  when: yay_version_cmd is failed
  shell: |
    rm -rf yay-bin
    git clone https://aur.archlinux.org/yay-bin.git
    cd yay-bin
    makepkg -si --noconfirm
    cd ..
    rm -rf yay-bin
